// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringMessage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_77cf58907c9fe205, []int{0}
}
func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (dst *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(dst, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type IntNum struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntNum) Reset()         { *m = IntNum{} }
func (m *IntNum) String() string { return proto.CompactTextString(m) }
func (*IntNum) ProtoMessage()    {}
func (*IntNum) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_77cf58907c9fe205, []int{1}
}
func (m *IntNum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntNum.Unmarshal(m, b)
}
func (m *IntNum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntNum.Marshal(b, m, deterministic)
}
func (dst *IntNum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntNum.Merge(dst, src)
}
func (m *IntNum) XXX_Size() int {
	return xxx_messageInfo_IntNum.Size(m)
}
func (m *IntNum) XXX_DiscardUnknown() {
	xxx_messageInfo_IntNum.DiscardUnknown(m)
}

var xxx_messageInfo_IntNum proto.InternalMessageInfo

func (m *IntNum) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type TestList struct {
	Value                []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestList) Reset()         { *m = TestList{} }
func (m *TestList) String() string { return proto.CompactTextString(m) }
func (*TestList) ProtoMessage()    {}
func (*TestList) Descriptor() ([]byte, []int) {
	return fileDescriptor_gateway_77cf58907c9fe205, []int{2}
}
func (m *TestList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestList.Unmarshal(m, b)
}
func (m *TestList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestList.Marshal(b, m, deterministic)
}
func (dst *TestList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestList.Merge(dst, src)
}
func (m *TestList) XXX_Size() int {
	return xxx_messageInfo_TestList.Size(m)
}
func (m *TestList) XXX_DiscardUnknown() {
	xxx_messageInfo_TestList.DiscardUnknown(m)
}

var xxx_messageInfo_TestList proto.InternalMessageInfo

func (m *TestList) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*StringMessage)(nil), "example.StringMessage")
	proto.RegisterType((*IntNum)(nil), "example.IntNum")
	proto.RegisterType((*TestList)(nil), "example.TestList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// YourServiceClient is the client API for YourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type YourServiceClient interface {
	Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
}

type yourServiceClient struct {
	cc *grpc.ClientConn
}

func NewYourServiceClient(cc *grpc.ClientConn) YourServiceClient {
	return &yourServiceClient{cc}
}

func (c *yourServiceClient) Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/example.YourService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YourServiceServer is the server API for YourService service.
type YourServiceServer interface {
	Echo(context.Context, *StringMessage) (*StringMessage, error)
}

func RegisterYourServiceServer(s *grpc.Server, srv YourServiceServer) {
	s.RegisterService(&_YourService_serviceDesc, srv)
}

func _YourService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YourServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.YourService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YourServiceServer).Echo(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _YourService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.YourService",
	HandlerType: (*YourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _YourService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestServiceClient interface {
	Echo(ctx context.Context, in *IntNum, opts ...grpc.CallOption) (*TestList, error)
}

type testServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestServiceClient(cc *grpc.ClientConn) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) Echo(ctx context.Context, in *IntNum, opts ...grpc.CallOption) (*TestList, error) {
	out := new(TestList)
	err := c.cc.Invoke(ctx, "/example.TestService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceServer is the server API for TestService service.
type TestServiceServer interface {
	Echo(context.Context, *IntNum) (*TestList, error)
}

func RegisterTestServiceServer(s *grpc.Server, srv TestServiceServer) {
	s.RegisterService(&_TestService_serviceDesc, srv)
}

func _TestService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntNum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.TestService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Echo(ctx, req.(*IntNum))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _TestService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_gateway_77cf58907c9fe205) }

var fileDescriptor_gateway_77cf58907c9fe205 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4f, 0x2c, 0x49,
	0x2d, 0x4f, 0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad, 0x48, 0xcc, 0x2d,
	0xc8, 0x49, 0x95, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f,
	0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x28, 0x53, 0x52, 0xe5, 0xe2,
	0x0d, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x12, 0xe1,
	0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94,
	0xe4, 0xb8, 0xd8, 0x3c, 0xf3, 0x4a, 0xfc, 0x4a, 0x73, 0x51, 0xe5, 0x99, 0x61, 0xf2, 0x0a, 0x5c,
	0x1c, 0x21, 0xa9, 0xc5, 0x25, 0x3e, 0x99, 0xc5, 0x25, 0xc8, 0x2a, 0x98, 0xe1, 0x26, 0x18, 0xc5,
	0x72, 0x71, 0x47, 0xe6, 0x97, 0x16, 0x05, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0xf9, 0x71,
	0xb1, 0xb8, 0x26, 0x67, 0xe4, 0x0b, 0x89, 0xe9, 0x41, 0xdd, 0xa9, 0x87, 0xe2, 0x0c, 0x29, 0x1c,
	0xe2, 0x4a, 0x62, 0x4d, 0x97, 0x9f, 0x4c, 0x66, 0x12, 0x50, 0xe2, 0xd6, 0x2f, 0x2d, 0x4e, 0x2d,
	0xd2, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0xb3, 0x62, 0xd4, 0x32, 0x0a, 0xe2, 0xe2, 0x06, 0x39, 0x00,
	0x66, 0xbc, 0x33, 0xd4, 0x78, 0x7e, 0xb8, 0x31, 0x10, 0xe7, 0x4b, 0x09, 0xc2, 0x05, 0x60, 0xee,
	0x55, 0x12, 0x07, 0x1b, 0x29, 0xa8, 0xc4, 0x03, 0x37, 0x32, 0xbf, 0xb4, 0xc4, 0x8a, 0x51, 0x2b,
	0x89, 0x0d, 0x1c, 0x44, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0x07, 0xb6, 0x65, 0x5a,
	0x01, 0x00, 0x00,
}
